name: "Build a Python Django project"
on:
  workflow_dispatch:

jobs:
  build:
    name: Start
    runs-on: ubuntu-latest
    environment:
       name: development
       url: ${{ steps.get-url.outputs.your_site }}
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          architecture: "x64"

      - name: Create project
        run: |
          pip install django
          django-admin startproject django_app .
          pip freeze > requirements.txt
          
      - name: Configure git
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          
      - name: Add app URL to Allowed Hosts
        run: |
          sed -i "s/\[]/['${{secrets.AZURE_APP_NAME}}.azurewebsites.net']/" ./django_app/settings.py
          
      - name: Commit code to repo
        run: |
          git add .
          git commit -m "Generate framework code and initialize workflows"
          git push
          
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_APP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          
      - name: Website URL
        run: |
          echo "Website URL: https://${{secrets.AZURE_APP_NAME}}.azurewebsites.net"
          
      - name: Wait for website to come online
        env:
            AZURE_APP_NAME: ${{ secrets.AZURE_APP_NAME }}
        timeout-minutes: 5 
        id: get-url
        run: |
          echo "Waiting for the website to come alive..."
          URL="https://${{ env.AZURE_APP_NAME }}.azurewebsites.net"
          sleep 20
          STATUS_CODE=$(curl -o /dev/null -s -w "%{http_code}\n" $URL)
          echo "STATUSCODE: $STATUS_CODE"
          while [ $STATUS_CODE -ne 200 ]
          do
            sleep 10
            STATUS_CODE=$(curl -o /dev/null -s -w "%{http_code}\n" $URL)
            echo "STATUSCODE: $STATUS_CODE"
          done
          echo "Website is up and running..."
          echo "Browse here: $URL"       
          echo "::set-output name=your_site::$URL"
